Agent
MattSScott/basePlatformSOMAS pull request #1
Opened 2023-07-25 10:35 UTC by ADimoska

2023-07-26 00:42 UTC, MattSScott requested changes
Really nice first implementation. Just a few changes to make

2023-07-26 00:42 UTC, MattSScott commented on pkg/infra/server/baseServer.go
> +	energy int
This is too specific - I think that this came from a previous Cohort. I'd remove them to keep the implementation general

2023-07-26 00:42 UTC, MattSScott commented on pkg/infra/server/baseServer.go
> +}
Same as before

2023-07-26 00:42 UTC, MattSScott commented on pkg/infra/server/baseServer.go
> +		bs.Agents[index].UpdateAgent()
Use the `element` variable you just created. Also, maybe label it as `agent`

2023-07-29 03:04 UTC, MattSScott requested changes
Again, good stuff, but a few parameters that are implementation specific that need removing

2023-07-29 03:04 UTC, MattSScott commented on pkg/agents/baseAgent.go
> +	Energy int
Please remove these - they are too specific

2023-07-29 03:04 UTC, MattSScott commented on pkg/agents/baseAgent.go
> +	}
Same as above

2023-08-01 13:15 UTC, ADimoska commented
Stale - new pull request submitted

2023-08-01 13:15 UTC, closed without merging